#ifndef FORGEKEY_OMS_COMMAND_PUBKEY_H
#define FORGEKEY_OMS_COMMAND_PUBKEY_H

#ifndef FORGEKEY_OMS_COMMAND_PUBKEY_PEM
#define FORGEKEY_OMS_COMMAND_PUBKEY_PEM \
"-----BEGIN PUBLIC KEY-----\n" \
"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEREPLACEMEREPLACEMEREPLACEMEREPLA\n" \
"CEMEREPLACEMEREPLACEMEREPLACEMEREPLACEMEREPLACEMEREPLACEMEREPLAC=\n" \
"-----END PUBLIC KEY-----\n"
#endif

static const char* kOmsCommandPubKeyPem = FORGEKEY_OMS_COMMAND_PUBKEY_PEM;

#endif
